<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <Version>2.0.0-preview.1</Version>
    <Authors>Project Launcher Contributors</Authors>
    <Product>Project Launcher</Product>
    <Copyright>Copyright (c) 2026 Project Launcher Contributors</Copyright>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <DebugType>embedded</DebugType>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
